# SPDX-FileCopyrightText: 2024 Petr Pucil <petr.pucil@seznam.cz>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "day05_print_queue"
version = "0.1.0"
edition = "2021"

[dependencies]
